on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.gitmodules'

name: Cleanup package server

jobs:
  update:
    name: Delete removed packages
    uses: tempbioc/workflows/.github/workflows/cleanup.yml@v1
    secrets: inherit
